# Generated by Django 2.2.11 on 2020-06-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=255, verbose_name='識別碼')),
                ('displayName', models.CharField(max_length=255, verbose_name='顯示名稱')),
                ('pictureUrl', models.CharField(max_length=255, verbose_name='大頭貼')),
                ('language', models.CharField(max_length=20, verbose_name='語言')),
                ('status', models.BooleanField(default=False, verbose_name='狀態')),
            ],
            options={
                'verbose_name': 'Line使用者',
                'verbose_name_plural': 'Line使用者',
            },
        ),
    ]
