# Generated by Django 2.2.11 on 2020-06-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0002_lineuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineuser',
            name='statusMessage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='lineuser',
            name='displayName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='顯示名稱'),
        ),
        migrations.AlterField(
            model_name='lineuser',
            name='language',
            field=models.CharField(blank=True, default='zh-Hant', max_length=20, null=True, verbose_name='語言'),
        ),
        migrations.AlterField(
            model_name='lineuser',
            name='pictureUrl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='大頭貼'),
        ),
        migrations.AlterField(
            model_name='lineuser',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='lineuser',
            name='userId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='識別碼'),
        ),
    ]
