server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    # 回應錯誤畫面不要顯示nginx的版本
    server_tokens off;

    access_log /var/log/nginx/default_access.log;
    error_log /var/log/nginx/default_error.log;

    return 404;
}
