version: "3.6"

volumes:
  coalb_postgres_data:
    name: coalb_postgres_volumes
  coalb_code_data:
    name: coalb_code_volumes

networks:
  coalb_backend:
    name: coalb_backend_networks

services:
  db:
    container_name: coalb_pg01
    image: postgres:10-alpine
    volumes:
      - coalb_postgres_data:/var/lib/postgresql/data
    env_file:
      - src/.env
    networks:
      - coalb_backend

  web:
    container_name: coalb_dg01
    image: coalb_web
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    # Same as the port runserver
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/code
    env_file:
      - src/.env
    networks:
      - coalb_backend
