version: "3.8"

name: "coalb_prod"

services:
    db:
        container_name: coalb_db
        image: postgres:10
        restart: always
        volumes:
            - ../../pgdata/db:/var/lib/postgresql/data
            - ../../pgdata/backup:/backup
        env_file:
            - ../../src/envs/prod.env
        networks:
            - backend_db

    web:
        container_name: coalb_web
        image: coalb-img
        build:
            context: ../../
            dockerfile: container/prod/Dockerfile
        restart: always
        expose:
            - 8000
        command: /code/scripts/start.sh
        entrypoint: /code/scripts/entrypoint.sh
        volumes:
            - ../../src/fixtures:/code/fixtures
            - ../../src/envs:/code/envs
            - ../../src/static:/code/static
            - ../../src/staticfiles:/code/staticfiles
            - ../../src/media:/code/media
            - ../../src/logs:/code/logs
        depends_on:
            - db
        networks:
            - frontend
            - backend_db
            - backend_selenium_chromium

    selenium:
        container_name: coalb_selenium
        image: seleniarm/standalone-chromium:123.0
        restart: always
        networks:
            - backend_selenium_chromium

    nginx:
        container_name: coalb_nginx
        image: nginx:latest
        restart: always
        ports:
            - 8000:80
            # - 4400:443
        volumes:
            - ./nginx/ssl:/etc/letsencrypt
            - ./nginx/logs:/var/log/nginx
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ../../src/staticfiles:/code/staticfiles
            - ../../src/media:/code/media
        networks:
            - frontend

# volumes:
#     staticfiles:
#         name: coalb-web-staticfiles

networks:
    backend_db:
        name: coalb-backend-network
    backend_app:
        name: coalb-backend-app-network
    frontend:
        name: coalb-frontend-network
    backend_selenium_chromium:
        name: backend-selenium-chromium-network
