version: "3.8"

name: "coalb_prod"

services:
    db:
        container_name: coalb_db
        image: postgres:10-alpine
        restart: always
        volumes:
            - ../../pgdata/db:/var/lib/postgresql/data
            - ../../pgdata/backup:/backup
        env_file:
            - ../../src/envs/prod.env
        networks:
            - backend

    web:
        container_name: coalb_web
        image: coalb-img
        restart: always
        build:
            context: ../../
            dockerfile: container/prod/Dockerfile
        expose:
            - 8000
        command: /code/scripts/start.sh
        entrypoint: /code/scripts/entrypoint.sh
        volumes:
            - ../../src/logs:/code/logs
            - ../../src/media:/code/media
            - staticfiles:/code/staticfiles
        depends_on:
            - db
        networks:
            - frontend
            - backend
            - backend_selenium_chromium

    # selenium:
    #     container_name: coalb_selenium
    #     image: seleniarm/standalone-chromium:123.0
    #     restart: always
    #     networks:
    #         - backend_app

    nginx:
        container_name: coalb_nginx
        image: matsuilin101/nginx-cert-bot:1.27.0
        restart: always
        ports:
            - 8020:80
            # - 4420:443
        volumes:
            - ./nginx/ssl:/etc/letsencrypt
            - ./nginx/log:/var/log/nginx
            - ./nginx/conf.d:/etc/nginx/conf.d
            - staticfiles:/code/staticfiles
        networks:
            - frontend

volumes:
    staticfiles:
        name: coalb-web-staticfiles

networks:
    backend:
        name: coalb-backend-network
    backend_app:
        name: coalb-backend-app-network
    frontend:
        name: coalb-frontend-network
    backend_selenium_chromium:
        name: backend-selenium-chromium-network
        external: true
