DJANGO_CONTAINER_NAME = coalb_web
NGINX_CONTAINER_NAME = coalb_nginx

bash:
		docker exec -it $(DJANGO_CONTAINER_NAME) bash

server:
		docker exec -it $(NGINX_CONTAINER_NAME) bash

sh:
		docker exec -it $(NGINX_CONTAINER_NAME) sh
