# Generated by Django 2.2.11 on 2021-01-22 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名稱')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='值')),
            ],
            options={
                'verbose_name': '抽象模型',
                'verbose_name_plural': '抽象模型',
            },
        ),
        migrations.CreateModel(
            name='ProduceValueCity',
            fields=[
                ('abstractmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coa.AbstractModel')),
                ('province', models.CharField(blank=True, max_length=20, null=True, verbose_name='省')),
                ('type', models.IntegerField(verbose_name='類型')),
            ],
            options={
                'verbose_name': '產值表-城市',
                'verbose_name_plural': '產值表-城市',
            },
            bases=('coa.abstractmodel',),
        ),
        migrations.CreateModel(
            name='ProduceValueFarmCategory',
            fields=[
                ('abstractmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coa.AbstractModel')),
            ],
            options={
                'verbose_name': '產值表-類別',
                'verbose_name_plural': '產值表-類別',
            },
            bases=('coa.abstractmodel',),
        ),
        migrations.CreateModel(
            name='ProduceValueProduct',
            fields=[
                ('abstractmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coa.AbstractModel')),
                ('category', models.CharField(max_length=50, verbose_name='分組類別')),
                ('city_type', models.IntegerField(verbose_name='城市類型')),
            ],
            options={
                'verbose_name': '產值表-產品',
                'verbose_name_plural': '產值表-產品',
            },
            bases=('coa.abstractmodel',),
        ),
    ]
