# Generated by Django 2.2.11 on 2021-01-21 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名稱')),
                ('value', models.CharField(max_length=255, verbose_name='值')),
            ],
            options={
                'verbose_name': '抽象模型',
                'verbose_name_plural': '抽象模型',
            },
        ),
        migrations.CreateModel(
            name='ProduceValueCity',
            fields=[
                ('abstractmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coa.AbstractModel')),
            ],
            options={
                'verbose_name': '產值表',
                'verbose_name_plural': '產值表',
            },
            bases=('coa.abstractmodel',),
        ),
    ]
