# Generated by Django 2.2.11 on 2021-01-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producevaluecity',
            name='province',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='省'),
        ),
    ]
