# Generated by Django 2.2.11 on 2021-01-21 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0002_producevaluecity_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceValueCategory',
            fields=[
                ('abstractmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coa.AbstractModel')),
            ],
            options={
                'verbose_name': '產值表-類別',
                'verbose_name_plural': '產值表-類別',
            },
            bases=('coa.abstractmodel',),
        ),
        migrations.AlterModelOptions(
            name='producevaluecity',
            options={'verbose_name': '產值表-城市', 'verbose_name_plural': '產值表-城市'},
        ),
    ]
