# Generated by Django 2.2.11 on 2021-01-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0003_auto_20210121_1201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProduceValueCategory',
            new_name='ProduceValueFarmCategory',
        ),
    ]
