# Generated by Django 2.2.11 on 2021-01-22 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0004_auto_20210121_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceValueProduct',
            fields=[
                ('abstractmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coa.AbstractModel')),
                ('category', models.CharField(max_length=50, verbose_name='分組類別')),
            ],
            options={
                'verbose_name': '產值表-產品',
                'verbose_name_plural': '產值表-產品',
            },
            bases=('coa.abstractmodel',),
        ),
        migrations.AlterField(
            model_name='abstractmodel',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='值'),
        ),
    ]
