# Generated by Django 2.2.11 on 2021-07-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0007_productcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, verbose_name='分類')),
                ('id_table', models.CharField(max_length=20, verbose_name='表格ID')),
                ('id_query', models.CharField(max_length=20, verbose_name='查詢ID')),
                ('value', models.CharField(max_length=20, verbose_name='值')),
                ('code', models.CharField(max_length=50, verbose_name='代碼')),
                ('name', models.CharField(max_length=50, verbose_name='名稱')),
            ],
            options={
                'verbose_name': '農耕作物',
                'verbose_name_plural': '農耕作物',
            },
        ),
    ]
