# Generated by Django 2.2.11 on 2021-07-02 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0007_productcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropPriceOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, verbose_name='分類')),
                ('id_table', models.CharField(max_length=20, verbose_name='表格ID')),
                ('id_query', models.CharField(max_length=20, verbose_name='查詢ID')),
                ('value', models.CharField(max_length=20, verbose_name='值')),
                ('code', models.CharField(max_length=50, verbose_name='代碼')),
                ('name', models.CharField(max_length=50, verbose_name='名稱')),
            ],
            options={
                'verbose_name': '農耕作物產地價',
                'verbose_name_plural': '農耕作物產地價',
            },
        ),
        migrations.CreateModel(
            name='CropPriceWholesale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_class', models.CharField(max_length=50, verbose_name='主分類')),
                ('sub_class', models.CharField(max_length=50, verbose_name='次分類')),
                ('level', models.PositiveIntegerField(verbose_name='級別')),
                ('name', models.CharField(max_length=20, verbose_name='名稱')),
                ('value', models.CharField(max_length=20, verbose_name='值')),
                ('search_name', models.CharField(max_length=20, verbose_name='搜尋名稱')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coa.CropPriceWholesale', verbose_name='上層物件')),
            ],
            options={
                'verbose_name': '農耕作物批發價',
                'verbose_name_plural': '農耕作物批發價',
            },
        ),
    ]
