# Generated by Django 2.2.11 on 2021-07-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0008_croppriceorigin_croppricewholesale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropProduceUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10, verbose_name='類別')),
                ('display_name', models.CharField(max_length=50, verbose_name='顯示名稱')),
                ('name', models.CharField(max_length=20, verbose_name='名稱')),
                ('period', models.CharField(blank=True, max_length=10, null=True, verbose_name='期作別')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
                ('district', models.CharField(blank=True, max_length=20, null=True, verbose_name='鄉鎮區')),
                ('city_district', models.CharField(blank=True, max_length=20, null=True, verbose_name='完整行政區名稱')),
                ('city_code', models.CharField(max_length=20, verbose_name='城市代碼')),
                ('district_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='鄉鎮區代碼')),
                ('amount_min', models.FloatField(default=0, verbose_name='產量最小值')),
                ('amount_max', models.FloatField(default=0, verbose_name='產量最大值')),
                ('amount_average', models.FloatField(default=0, verbose_name='產量平均值')),
                ('amount_unit', models.CharField(default='(公斤/公頃)', max_length=20, verbose_name='產量單位')),
                ('value_min', models.FloatField(default=0, verbose_name='產值最大值')),
                ('value_max', models.FloatField(default=0, verbose_name='產值最小值')),
                ('value_average', models.FloatField(default=0, verbose_name='產值平均值')),
                ('value_unit', models.CharField(default='(元/公頃)', max_length=20, verbose_name='產值單位')),
            ],
            options={
                'verbose_name': '農耕作物產值產量表',
                'verbose_name_plural': '農耕作物產值產量表',
            },
        ),
    ]
