# Generated by Django 2.2.11 on 2021-07-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0010_totalvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropProduceTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名稱')),
                ('value', models.CharField(max_length=10, verbose_name='值')),
            ],
            options={
                'verbose_name': '作物產量作物清單',
                'verbose_name_plural': '作物產量作物清單',
            },
        ),
    ]
