# Generated by Django 2.2.24 on 2022-09-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0011_cropproducetotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropcost',
            name='end_year',
            field=models.IntegerField(null=True, verbose_name='結束年'),
        ),
        migrations.AddField(
            model_name='cropcost',
            name='start_year',
            field=models.IntegerField(null=True, verbose_name='起始年'),
        ),
    ]
