# Generated by Django 2.2.24 on 2022-09-29 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0012_auto_20220928_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractmodel',
            options={'ordering': ['id'], 'verbose_name': '抽象模型', 'verbose_name_plural': '抽象模型'},
        ),
        migrations.AlterModelOptions(
            name='cropcost',
            options={'ordering': ['id'], 'verbose_name': '農畜產品生產成本統計', 'verbose_name_plural': '農畜產品生產成本統計'},
        ),
        migrations.AlterModelOptions(
            name='croppriceorigin',
            options={'ordering': ['id'], 'verbose_name': '農耕作物產地價', 'verbose_name_plural': '農耕作物產地價'},
        ),
        migrations.AlterModelOptions(
            name='croppricewholesale',
            options={'ordering': ['id'], 'verbose_name': '農耕作物批發價', 'verbose_name_plural': '農耕作物批發價'},
        ),
        migrations.AlterModelOptions(
            name='cropproducetotal',
            options={'ordering': ['id'], 'verbose_name': '作物產量作物清單', 'verbose_name_plural': '作物產量作物清單'},
        ),
        migrations.AlterModelOptions(
            name='cropproduceunit',
            options={'ordering': ['id'], 'verbose_name': '農耕作物產值產量表', 'verbose_name_plural': '農耕作物產值產量表'},
        ),
        migrations.AlterModelOptions(
            name='livestockbyproduct',
            options={'ordering': ['id'], 'verbose_name': '畜禽副產品產量', 'verbose_name_plural': '畜禽副產品產量'},
        ),
        migrations.AlterModelOptions(
            name='livestockfeedamount',
            options={'ordering': ['id'], 'verbose_name': '畜禽飼養頭數', 'verbose_name_plural': '畜禽飼養頭數'},
        ),
        migrations.AlterModelOptions(
            name='livestockfeedlot',
            options={'ordering': ['id'], 'verbose_name': '畜禽飼養場數', 'verbose_name_plural': '畜禽飼養場數'},
        ),
        migrations.AlterModelOptions(
            name='livestockslaughter',
            options={'ordering': ['id'], 'verbose_name': '畜禽供應屠宰頭數', 'verbose_name_plural': '畜禽供應屠宰頭數'},
        ),
        migrations.AlterModelOptions(
            name='producevaluecity',
            options={'ordering': ['id'], 'verbose_name': '產值表-城市', 'verbose_name_plural': '產值表-城市'},
        ),
        migrations.AlterModelOptions(
            name='producevaluefarmcategory',
            options={'ordering': ['id'], 'verbose_name': '產值表-類別', 'verbose_name_plural': '產值表-類別'},
        ),
        migrations.AlterModelOptions(
            name='producevalueproduct',
            options={'ordering': ['id'], 'verbose_name': '產值表-產品', 'verbose_name_plural': '產值表-產品'},
        ),
        migrations.AlterModelOptions(
            name='productcode',
            options={'ordering': ['id'], 'verbose_name': '作物代碼', 'verbose_name_plural': '作物代碼'},
        ),
        migrations.AlterModelOptions(
            name='totalvalue',
            options={'ordering': ['id'], 'verbose_name': '總產值', 'verbose_name_plural': '總產值'},
        ),
    ]
