# Generated by Django 2.2.28 on 2025-03-01 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0013_auto_20220929_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockfeedamount',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coa.LivestockFeedAmount', verbose_name='上層物件'),
        ),
    ]
