# Generated by Django 2.2.11 on 2020-12-21 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='LINE識別碼')),
                ('display_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='顯示名稱')),
                ('picture_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='大頭貼')),
                ('status_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='狀態')),
                ('language', models.CharField(blank=True, default='zh-Hant', max_length=20, null=True, verbose_name='語言')),
                ('status', models.BooleanField(blank=True, default=False, null=True, verbose_name='狀態')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': 'Line使用者',
                'verbose_name_plural': 'Line使用者',
            },
        ),
        migrations.CreateModel(
            name='SD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('layer', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='line.SD')),
            ],
        ),
    ]
