# Generated by Django 2.2.24 on 2021-07-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名稱')),
                ('value', models.CharField(max_length=255, verbose_name='值')),
            ],
            options={
                'verbose_name': '特殊設定',
                'verbose_name_plural': '特殊設定',
            },
        ),
    ]
