# Generated by Django 2.2.24 on 2021-07-13 06:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='資料庫名稱')),
                ('status', models.BooleanField(default=False, verbose_name='狀態')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='開始時間')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('expire_time', models.DateTimeField(default=datetime.datetime(2021, 7, 13, 6, 33, 25, 664878, tzinfo=utc), verbose_name='過期時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
            ],
            options={
                'verbose_name': '資料庫鎖定',
                'verbose_name_plural': '資料庫鎖定',
            },
        ),
    ]
