# Generated by Django 2.2.24 on 2021-07-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210714_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasecontrol',
            name='expire_time',
            field=models.DateTimeField(verbose_name='過期時間'),
        ),
    ]
