# Generated by Django 2.2.11 on 2020-12-21 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('line', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineBodyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='接收內容')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line.LineUser', verbose_name='LINE使用者')),
            ],
            options={
                'verbose_name': 'LINE接收訊息記錄',
                'verbose_name_plural': 'LINE接收訊息記錄',
            },
        ),
    ]
