# Generated by Django 2.2.11 on 2020-12-22 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0001_initial'),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineMessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=64, verbose_name='訊息識別碼')),
                ('reply_token', models.CharField(max_length=64, verbose_name='回應字段')),
                ('message', models.TextField(verbose_name='訊息內容')),
                ('reply', models.TextField(verbose_name='回應內容')),
                ('status', models.BooleanField(default=True, verbose_name='狀態')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line.LineUser', verbose_name='LINE使用者')),
            ],
            options={
                'verbose_name': 'LINE文字訊息記錄',
                'verbose_name_plural': 'LINE文字訊息記錄',
            },
        ),
    ]
