# Generated by Django 2.2.11 on 2020-12-22 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0001_initial'),
        ('log', '0002_linemessagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineFollowLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_token', models.CharField(blank=True, max_length=64, null=True, verbose_name='回應字段')),
                ('message', models.CharField(max_length=10, verbose_name='好友狀態')),
                ('reply', models.TextField(verbose_name='錯誤訊息')),
                ('status', models.BooleanField(default=True, verbose_name='狀態')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line.LineUser', verbose_name='LINE使用者')),
            ],
            options={
                'verbose_name': 'LINE好友狀態記錄',
                'verbose_name_plural': 'LINE好友狀態記錄',
            },
        ),
    ]
