# Generated by Django 2.2.24 on 2021-07-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20210720_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='linemessagelog',
            name='reply_at',
            field=models.DateTimeField(auto_now=True, verbose_name='回應時間'),
        ),
    ]
