# Generated by Django 2.2.28 on 2025-04-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_linemessagelog_reply_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255, verbose_name='關聯app')),
                ('message', models.TextField(verbose_name='內容')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '代理內容記錄',
                'verbose_name_plural': '代理內容記錄',
            },
        ),
    ]
