# Generated by Django 2.2.28 on 2025-04-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_proxylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxylog',
            name='response',
            field=models.TextField(default='', verbose_name='回應'),
        ),
    ]
